import { Categoria } from "@/services/NotificationService";

// ─── Tipos de evento por categoria ───────────────────────────────────────────

export const TIPOS_POR_CATEGORIA: Record<Categoria, string[]> = {
  DOENÇA: [
    "Muitos casos de gripe",
    "Muitos casos de diarreia", 
    "Suspeita de água contaminada",
    "Caso de varicela (catapora)", 
    "Suspeita sarampo/rubéola", 
    "Evento adverso pós-vacina", 
    "Óbito suspeito por Arbovirose", 
    "Aumento em comum de dengue", 
    "Presença de muitos vetores", 
    "Muitos casos de Leptospirose", 
    "Muitos casos de Leishmaniose", 
    "Muitas pessoas doentes com sintomas semelhantes", 
    "Doença desconhecida", 
    "Outro", 
  ],
  EPIZOOTIA: [
    "Morte de animais", 
    "Muitos animais mortos no mesmo local", 
    "Suspeita de raiva animal", 
    "Animais silvestres doentes", 
    "Mortes de aves", 
    "Doença em rebanhos", 
    "Grande quantidade de morcegos",
    "Outros",
  ],
  DESASTRE: [
    "Alagamento de casas" ,
    "Enchente/inundação" ,
    "Deslizamento de terra ",
    "Desabamento",
    "Risco estrutural",
    "Incêndio em mata",
    "Fumaça intensa",
    "Ventos fortes",
    "Outro",
  ],
};

export const LOCAIS_OCORRENCIA = [
  "Casa",
  "Trabalho",
  "Escola",
  "Via Pública",
  "Indústria",
  "Hospital",
  "Unidades de Atenção Primária à Saúde",
  "Igreja",
  "Evento/festa",
  "Restaurante/lanchonete",
  "Abrigo",
  "Sítio",
  "Fazenda",
  "Outros",
];

export const MEIOS_IDENTIFICACAO = [
  "Observação em visita domiciliar",
  "Informação da comunidade",
  "Escola/creche",
  "Unidade de saúde",
  "Liderança comunitária",
  "Rede social/mensagem",
  "Outro",
];

export const CONTINUIDADE_OPTIONS = ["Sim", "Não", "Não sei"];

export interface WizardData {
  categoria: Categoria | null;
  tipo_evento: string;
  data_aproximada: string;
  pessoas_animais: string;
  local_ocorrencia: string;
  estado?: "Ceará";
  municipio: string;
  endereco: string;
  latitude?: number;
  longitude?: number;
  meio_identificacao: string;
  continuidade_situacao: string;
  descricao: string;
  transcricao: string;
  medias: MediaAnexo[];
  nome: string;
  rascunho: boolean;
}

export const WIZARD_INITIAL: WizardData = {
  categoria: null,
  tipo_evento: "",
  data_aproximada: "",
  pessoas_animais: "",
  local_ocorrencia: "",
  endereco: "",
  latitude: undefined,
  estado: "Ceará",
  municipio: "",
  longitude: undefined,
  meio_identificacao: "",
  continuidade_situacao: "Não sei",
  descricao: "",
  transcricao: "",
  medias: [],
  nome: "",
  rascunho: false,
};

export interface MediaAnexo {
  uri: string;
  name: string;
  type: string;
  thumb?: string;
}



export const MUNICIPIOS_CEARA = [
  "Abaiara",
  "Acarape",
  "Acaraú",
  "Acopiara",
  "Aiuaba",
  "Alcântaras",
  "Altaneira",
  "Alto Santo",
  "Amontada",
  "Antonina do Norte",
  "Apuiarés",
  "Aquiraz",
  "Aracati",
  "Aracoiaba",
  "Ararendá",
  "Araripe",
  "Aratuba",
  "Arneiroz",
  "Assaré",
  "Aurora",
  "Baixio",
  "Banabuiú",
  "Barbalha",
  "Barreira",
  "Barro",
  "Barroquinha",
  "Baturité",
  "Beberibe",
  "Bela Cruz",
  "Boa Viagem",
  "Brejo Santo",
  "Camocim",
  "Campos Sales",
  "Canindé",
  "Capistrano",
  "Caridade",
  "Cariré",
  "Caririaçu",
  "Cariús",
  "Carnaubal",
  "Cascavel",
  "Catarina",
  "Catunda",
  "Caucaia",
  "Cedro",
  "Chaval",
  "Choró",
  "Chorozinho",
  "Coreaú",
  "Crateús",
  "Crato",
  "Croatá",
  "Cruz",
  "Deputado Irapuan Pinheiro",
  "Ereré",
  "Eusébio",
  "Farias Brito",
  "Forquilha",
  "Fortaleza",
  "Fortim",
  "Frecheirinha",
  "General Sampaio",
  "Graça",
  "Granja",
  "Granjeiro",
  "Groaíras",
  "Guaiúba",
  "Guaraciaba do Norte",
  "Guaramiranga",
  "Hidrolândia",
  "Horizonte",
  "Ibaretama",
  "Ibiapina",
  "Ibicuitinga",
  "Icapuí",
  "Icó",
  "Iguatu",
  "Independência",
  "Ipaporanga",
  "Ipaumirim",
  "Ipu",
  "Ipueiras",
  "Iracema",
  "Irauçuba",
  "Itaiçaba",
  "Itaitinga",
  "Itapajé",
  "Itapipoca",
  "Itapiúna",
  "Itarema",
  "Itatira",
  "Jaguaretama",
  "Jaguaribara",
  "Jaguaribe",
  "Jaguaruana",
  "Jardim",
  "Jati",
  "Jijoca de Jericoacoara",
  "Juazeiro do Norte",
  "Jucás",
  "Lavras da Mangabeira",
  "Limoeiro do Norte",
  "Madalena",
  "Maracanaú",
  "Maranguape",
  "Marco",
  "Martinópole",
  "Massapê",
  "Mauriti",
  "Meruoca",
  "Milagres",
  "Milhã",
  "Miraíma",
  "Missão Velha",
  "Mombaça",
  "Monsenhor Tabosa",
  "Morada Nova",
  "Moraújo",
  "Morrinhos",
  "Mucambo",
  "Mulungu",
  "Nova Olinda",
  "Nova Russas",
  "Novo Oriente",
  "Ocara",
  "Orós",
  "Pacajus",
  "Pacatuba",
  "Pacoti",
  "Pacujá",
  "Palhano",
  "Palmácia",
  "Paracuru",
  "Paraipaba",
  "Parambu",
  "Paramoti",
  "Pedra Branca",
  "Penaforte",
  "Pentecoste",
  "Pereiro",
  "Pindoretama",
  "Piquet Carneiro",
  "Pires Ferreira",
  "Poranga",
  "Porteiras",
  "Potengi",
  "Potiretama",
  "Quiterianópolis",
  "Quixadá",
  "Quixelô",
  "Quixeramobim",
  "Quixeré",
  "Redenção",
  "Reriutaba",
  "Russas",
  "Saboeiro",
  "Salitre",
  "Santa Quitéria",
  "Santana do Acaraú",
  "Santana do Cariri",
  "São Benedito",
  "São Gonçalo do Amarante",
  "São João do Jaguaribe",
  "São Luís do Curu",
  "Senador Pompeu",
  "Senador Sá",
  "Sobral",
  "Solonópole",
  "Tabuleiro do Norte",
  "Tamboril",
  "Tarrafas",
  "Tauá",
  "Tejuçuoca",
  "Tianguá",
  "Trairi",
  "Tururu",
  "Ubajara",
  "Umari",
  "Umirim",
  "Uruburetama",
  "Uruoca",
  "Varjota",
  "Várzea Alegre",
  "Viçosa do Ceará",
];
